version: '2'
services:
  ui:
    build: ./ui
    ports:
      - '8084:80'
    depends_on:
      - api
  api:
    container_name: api_prod
    build: ./api
    ports:
      - '8080:8080'
    volumes:
      - ./uploads:/usr/uploads/
    environment:
      - UPLOADS_DIR=/usr/uploads
      - MONGO_URL=mongodb://mongo:27017/liptov-zije
      - REACT_APP_BACKEND_ENDPOINT=http://89.221.222.30:8080
      - JWT_KEY=mykye1
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'