version: '2'
services:
  ui_base:
    container_name: dev_ui_base
    image: node:11
    volumes:
      - ./ui:/usr/src/service/
    working_dir: /usr/src/service/

  ui_dev:
    container_name: dev_ui
    extends:
      service: ui_base
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_ENDPOINT=http://localhost:8080
    command: npm start
    depends_on:
      - api_dev
      - ui_install

  ui_install:
    container_name: dev_ui_install
    extends:
      service: ui_base
    command: npm install
    depends_on:
      - api_dev

  api_base:
    container_name: dev_api_base
    image: node:11
    volumes:
      - ./uploads:/usr/uploads/
      - ./api:/usr/src/service/
    working_dir: /usr/src/service/
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=8080
      - UPLOADS_DIR=/usr/uploads
      - MONGO_URL=mongodb://host.docker.internal:27017/liptov-zije
      - JWT_KEY=mykye1

  api_dev:
    container_name: dev_api
    extends:
      service: api_base
    ports:
      - '8080:8080'
      - '27017:27017'
      - '56745:56745'
    command: npm run dev
    depends_on:
      - "api_install"

  api_install:
    container_name: dev_api_install
    extends:
      service: api_base
    command: npm install
