version: '2'
services:
  ui:
    build: ui
    ports:
      - '3000:3000'
    depends_on:
      - api
  api:
    build: api
    ports:
      - '8080:8080'
    environment:
      - MONGO_URL=mongodb://mongo:27017/liptov-zije
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '2717:27017'