version: '2'
services:
  ui:
    container_name: ui_prod
    build:
      context: ./ui
      args:
        - REACT_APP_BACKEND_ENDPOINT=http://89.221.222.30:8080
    ports:
      - '80:80'
#    environment:
#      - REACT_APP_BACKEND_ENDPOINT=http://89.221.222.30:8080
    depends_on:
      - api
  api:
    container_name: api_prod
    build: ./api
    ports:
      - '8080:8080'
    volumes:
      - ./uploads:/usr/uploads/
    environment:
      - UPLOADS_DIR=/usr/uploads
      - MONGO_URL=mongodb://mongo:27017/liptov-zije
      - JWT_KEY=mykye1
    depends_on:
      - mongo
  mongo:
    container_name: mongo_prod
    image: mongo
    ports:
      - '27017:27017'