version: '2'
services:
  ui:
    build: ui
    ports:
      - '3000:3000'
    depends_on:
      - dev

  base:
    image: node:11
    volumes:
      - ./api:/usr/src/service/
    working_dir: /usr/src/service/
    environment:
      - MONGO_URL=mongodb://host.docker.internal:27017/liptov-zije
      - JWT_KEY=mykye1

  dev:
    extends:
      service: base
    ports:
      - '8080:8080'
      - '27017:27017'
      - '56745:56745'
    command: npm run dev

  install:
    extends:
      service: base
    command: npm install
